- .vscode/launch.json
> Error: launch: program 'SOME_PATH\aspnetcore-angular2-universal\bin\Debug\netcoreapp1.0\aspnetcore-angular2-starter.dll' does not exist:
right path for this build is: 'SOME_PATH\aspnetcore-angular2-universal\bin\Debug\netcoreapp1.0\aspnetcore-angular2-universal.dll'
> fix on launch.json

- webpack.config.vendor.js
Hi, @Mark
I have made a mistake.
That is trying to get all CSS libraries automatically, but it is not working.
So, just reverted the work for that.
Please check and update it.
Thanks :)
> Vendor.css not generated issue solve

- package.json
> fix e2e test

- README.md
- app.json
Provide Heroku deploy configuration + add 'Deployment' section to README.  As part of #80
> added 'Deploy on Heroku'

- src/Angular2Spa/webpack.config.js
- src/Angular2Spa/webpack.config.test.js
- src/Angular2Spa/webpack.config.test.vendor.js
- src/Angular2Spa/webpack.config.vendor.js
Detail-
http://stackoverflow.com/questions/42076879/fallbackloader-option-has-been-deprecated-replace-with-fallback
> Webpack Deprication Notice Removed

- src/AspCoreServer/prepublish.cmd
Solve this issue-
https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/110#issuecomment-284267280
> Merge error solution

- Angular2Spa.sln
- src/Angular2Spa/Client/containers/chat/chat.component.html
Got the solution from here-
http://stackoverflow.com/a/1808352/2193439
> Set default project to "AspCoreServer"

- src/AspCoreServer/project.json
Publish getting error - solved
> ASP.Net Publish option is getting error

- Asp2017.csproj
> Update Nuget packages

- .vscode/launch.json
- .vscode/tasks.json
Development and production debug config files added for vsc
> Added Visual Studio Code debug config files

- Client/main.server.aot.ts
- webpack.config.js
Implements the fixes specified in #176.
> AOT build fixes

- Startup.cs
For some reason, it did not like the static files being set up at the bottom after the swagger changes. It seems to work as expected now
> Assets not loading bug

- README.md
See this issue link, https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/190.
> Modified FAQ

- tsconfig.json
- webpack.config.js
- webpack/webpack.aot.js
- webpack/webpack.client.js
I needed to make these changes to get it to build properly on Linux.
> fixed file paths for case sensitive filesystems

- Client/app/app.module.ts
- Client/app/components/navmenu/navmenu.component.html
- Client/app/containers/+lazy/lazy.component.ts
- Client/app/containers/+lazy/lazy.module.ts
- Client/main.browser.ts
closes #191
updates #165 (still needs to have speed improved)
> feat(lazy-loading): add lazy demo and fixed HMR

- Client/app/app.module.ts
- Client/app/components/navmenu/navmenu.component.html
- Client/app/containers/ngx-bootstrap-demo/ngx-bootstrap.component.html
- Client/app/containers/ngx-bootstrap-demo/ngx-bootstrap.component.ts
Just updated some of the namings as I seen the library name has been updated and it has been changed on the menu but not elsewhere
> Updated naming for ngx-bootstrap

- README.md
Just a small mention of Swagger should be enough?
> Updated documentation to mention swagger

- webpack/webpack.server.js
I seem to have missed this one in the last commit
> another path change

- Client/app/components/user-detail/user-detail.component.ts
Fixed error handling to actually show the alert, on error.
> User Rest API Demo - Error Handling

- Client/app/app.module.ts
- Client/app/containers/home/home.component.html
- package.json
Simply created a clean fork. The only changes were to replace ng2-bootstrap with ngx-bootstrap in package.json and any text references to "ng2-bootstrap" in the readme. Everything worked. So, that's all I did. Closes #226
> Replaced ng2-bootstrap with ngx-bootstrap.

- Server/Controllers/HomeController.cs
- Startup.cs
It is important for SEO that page.com/sitemap.xml exist
Of course you can have a sitemap.xml in the root directory, but a better way is to generate the sitemap dynamically. I mapped the route sitemap.xml to a method in the HomeController that returns a simple example of a sitemap.xml file
> added simple example of sitemap.xml

- Client/app/app.component.scss
- Client/app/components/navmenu/navmenu.component.css
- Client/app/components/navmenu/navmenu.component.html
- Client/app/components/navmenu/navmenu.component.ts
The goal of this pull request is to provide some basic updates to better support the navbar when the display width is less than 768px.  The changes occur in two areas.
1.Changes to the top level scss file to support multiple display widths.  
2.Changes to the navmenu component to make the 'hamburger' menu visible on mobile displays.
> Navbar Support for Small Displays

- README.md
we can leave this open until #376 is complete
> update to readme to clean up some things

- ClientApp/app/components/navmenu/navmenu.component.html
- ClientApp/app/components/navmenu/navmenu.component.ts
Minor updates related to the menu when in a mobile size display.  When a menu item is selected this update causes the menu to automatically collapse.
This PR should look a little better...
> Auto Close Menu on Select

- ClientApp/app/app.module.browser.ts
- ClientApp/app/app.module.server.ts
- ClientApp/polyfills/temporary-aspnetcore-engine.ts
- Server/Controllers/HomeController.cs
- Views/Shared/_Layout.cshtml
- package.json
🎁 🎁 
Added functionality to make sure (the temporary) aspnetcore-engine grabs scripts from the head, since preboot for example puts its code there to make its magic work.
Now we have preboot working as it should 👍
> feat(preboot): add preboot functionality & fix aspnetcore-engine

- .angular-cli.json
- ClientApp/tsconfig.app.json
Pull request for adding tslint config and tslint.app.json.
Note: I didn't fix all the linting errors there are when you run ng lint.   I could do that in another PR
> adding tslint config to angular-cli for the ng lint command

- Asp2017.csproj
https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch
> Allow for dotnet watch run command.

- webpack.config.js
PR to fix #543 .
Changelog:
- moved context replacement plugin to dev builds only
> Should fix #543

- Startup.cs
> browser caching

- .vscode/tasks.json
Solution for #658.
Small, yet critical fix for beginners who's trying to get started with VSC.
> Fix for #658

- ClientApp/tsconfig.app.json
> fix production build (#685)

- README.md
Updated the "FAQ" and "Consulting & Training" links in the README.md.
> Updated README.md table of content links

- Views/Shared/_Layout.cshtml
Just to follow established routes:
https://blogs.msdn.microsoft.com/ieinternals/2011/07/18/best-practice-get-your-head-in-order/
Thanks!
> feat(charset): move declaration to top
